apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - rbac.yaml
  - sync.yaml
  - sis.yaml
  - gosec.yaml
  - stratio-panel-ui.yaml
  - stratio-home.yaml
  - monitoring.yaml
labels:
  - pairs:
      toolkit.fluxcd.io/tenant: system-services
